# Generated by Django 6.0.1 on 2026-01-29 15:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affluenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ore_totali', models.DecimalField(decimal_places=2, help_text='Ore totali del giorno', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('assenze', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ore di assenza', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Affluenza',
                'verbose_name_plural': 'Affluenze',
                'ordering': ['-data'],
            },
        ),
    ]
