# Generated by Django 6.0.1 on 2026-01-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_profile', '0001_initial'),
        ('affluenza', '0001_initial'),
        ('partecipante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affluenza',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affluenze_create', to='admin_profile.admin'),
        ),
        migrations.AddField(
            model_name='affluenza',
            name='partecipante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affluenza_set', to='partecipante.partecipante'),
        ),
        migrations.AlterUniqueTogether(
            name='affluenza',
            unique_together={('partecipante', 'data')},
        ),
    ]
