# Generated by Django 6.0.1 on 2026-01-30 15:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_profile', '0001_initial'),
        ('partecipante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ore_totali', models.DecimalField(decimal_places=2, help_text='Ore totali del giorno', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('assenze', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ore di assenza', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registri_create', to='admin_profile.admin')),
                ('partecipante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_set', to='partecipante.partecipante')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registri',
                'ordering': ['-data'],
                'unique_together': {('partecipante', 'data')},
            },
        ),
    ]
