# Generated by Django 6.0.1 on 2026-01-29 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partecipante',
            fields=[
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='partecipante_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profilo', models.TextField(blank=True, help_text='Bio o informazioni aggiuntive', null=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partecipante',
                'verbose_name_plural': 'Partecipanti',
            },
        ),
    ]
